name = "trendy_command_line"
description = "Shiny new project"
version = "0.0.0"

authors = ["Paul Jarrett"]
maintainers = ["Paul Jarrett <jarrett.paul.young@gmail.com>"]
maintainers-logins = ["pyjarrett"]

executables = ["trendy_command_line"]

[[depends-on]]  # This line was added by `alr with`
trendy_test = "~0.0.0"  # This line was added by `alr with`
